sudo: required
language: ruby
services:
- docker
install:
- echo "install nothing!"
script:
- echo "no tests!"
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region us-east-1)
- docker build -t redify .
- docker tag redify:latest 221120016444.dkr.ecr.eu-west-1.amazonaws.com/redify:latest
- docker push 221120016444.dkr.ecr.eu-west-1.amazonaws.com/redify:latest
env:
  AWS_ACCESS_KEY_ID:
    secure: QyZkCdZP8mdsPx3lRyGA/M3EdANmm2DklTjUoxfTQIVomyYg+fRBgrcS1KcLpWMMaGl3+fb+GTizGNGgsQkfylJzRzq5zO23xuVAG5q+rNxwmcpTRxAHsNF6l8FXrA+qjik8tx/5hHGUdl505BjV2NYNjH97JVYd8dQIfKsB/XTOfaxqceSXm0FmX7YE+Eb2nc3NSRew+RNNy5RSUTrULAWtIF3UZV7ZT9uYe4t7Xjx22U7BhVxogta+di9uUFWJZy9X9kFJkOra3H3hyDBqJYOPJgLE5qLp/4KZwv2PP5eAONB7axoyxVqUtyv7u1TObX+ekKVAvJq7FWOiW9UPgY5TqR8wDPR2EJVS0/XQs2bxZjr/OeWFuB0NsZc6DUxx0c/ohsyPU5hNPFpWXtH+/yUrcnZNDOKmRWkcK3xikAsbzRXAEJvEQLlOVi3G/298RZEa1DkXPoUSRMyvAbfr1Pb3kC3TQlcVIEEGPBqBN/sjPfkQbElMWr0mTVUlruvlZNNnvSkZH07rgJ/qv4Tx5pVkUNibvebVtolhV1LnHSGWBJuyudX2qKqSQ8828Mpbz+X4RLVHPqYUrzbJGQWMoVFonbnL6gj7THDqosUfufD4suN23z9/Pt7fWtdwFEVy+XQsS6cfStId1jT6N43iEG8KbJBhQgrt0WVBzZYBJpw=
  AWS_SECRET_ACCESS_KEY:
    secure: achkOr8ESHUn1pweS1nz29j9+elEZn426nq35gpsTZISk6tfT5ouGVEOPmVwwfxXmCVzCzF19fbnfJvHBJ6q4YK3Rot1X/3JMIynSYw1G9/FnLtHMIwM3mWZD+Aify01ig/hMpzAtBtBKOMKEMxJ55MxB1sNP2a+vZBuiPLngJ/QBLc/FD4+FBVsPwU9s2zNDADPT3rn3q2QKzfJQHPoNJDop8Q1A10Mlwy4DPcZv9065eddKn4H3tmaANghlGbz0+0uHxnK67Kin7xZdyxDIVCPxyHI9wjZY2qEk6LEcINoH95Girf0QlRc9O17HSnB778MiH93c5pkfypExXmc9BpqyTBt5PJqPO65/4HX0ecDlST2WC4oCd0pvcZz5D646M7bkoSVR356SAEjjvhDXH2K4sr+SpZheSGJS6NOK/Z3dNy4qhCqXcAyH1MGUHQrL25QqC8tPUsAzvNYM+epLKP6c5I1i9CA5cTNYlzf3GNk4AKRHHfCApZEieUTXVk5NQ74A9Zfn8GyZQW78pBPaTsXws0HwPI8yU2UdSyBp7c8BD2LCzP0hGcoECggTlX6I+qikFeVeCtgLJ4ltif2hMo1hzw6W/hvo3BSY1+U9nglpl7OsGkFiCt2O+YUToOl54kKn+9eAAD7PfRB6PVFwkkjHmfz1ovLTA1WbcOBDPA=
