---
version: 0.2
phases:
  install:
    commands:
      - gem install bundler
      - RAILS_ENV=development bundle install
      # - gem install rspec
  build:
    commands:
  post_build:
    commands:
      - echo Build completed on `date`
